### ISSUE TITLE
引数をオプションにして欲しい

### ISSUE THREAD

**Issue by thinca** [deris/vim-rengbang#7]
引数の順番が覚えられないので、`--start 1` みたいな指定ができるようにして、引数名を補完できるようにして欲しいです。
これが便利です。
https://github.com/vim-jp/vital.vim/blob/master/doc/vital-option_parser.txt

**Comment by deris** [comment]
私も覚えられないので常々何か解決策はないかと思っていました。
引数名補完はいい案ですね。
既存との互換をどうするかが悩みどころですが。。。

**Comment by thinca** [comment]
既存の引数の `pattern` や `format` に `--` を使う頻度を考えると、互換性はそんなに気にしなくていい気がしてます。`--` で始まってたらオプション、そうでなければ今まで通り、という感じでどうでしょう?

**Comment by deris** [comment]
アドバイスありがとうございます。
試しに[named_option](https://github.com/deris/vim-rengbang/tree/named_option)ブランチで実装してみました。
以下の様な感じで実行できます。
```vim
:%RengBang --pattern=\d\+ --start-number=0 --step-count=1 --use-first --format=%d
```
ドキュメントなどはまだないです。テストも。。。まだないです。
異常系はかなり怪しいです。。。

**Comment by deris** [comment]
あ、肝心のOptionParserコミット漏れてた…

**Comment by deris** [comment]
すかさず```git push -f```しました。

**Comment by deris** [comment]
[named_option](https://github.com/deris/vim-rengbang/tree/named_option)ブランチで、既存の引数とオプションを混ぜて使えるようにしてみました。

**Comment by deris** [comment]
masterにマージしたのでcloseしました。

**Comment by thinca** [comment]
:+1:
